spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
  logging:
    loki:
      url: ${LOKI_URL}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: profile_image, profile_nickname
management:
  endpoints:
    web:
      exposure:
        include: prometheus
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: LinkHub-server-local
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  application:
    name: LinkHub-server-prod
---
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      space-default-image-path: ${SPACE_DEFAULT_IMAGE_PATH}
      member-default-image-path: ${MEMBER_DEFAULT_IMAGE_PATH}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret:
    ${JWT_SECRET}
  expiration:
    ${JWT_EXPIRATION}

server:
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true

kakao:
  admin-key:
    ${KAKAO_ADMIN_KEY}
